### ISSUE TITLE
Add builds for macOS x86_64

### ISSUE THREAD

**Issue by lpsinger** [Intelligence-AI/jsonschema#76]
Would you please add builds for macOS x86_64?

```
$ npx @intelligence-ai/jsonschema --help
The JSON Schema CLI NPM package does not support darwin for x86_64 yet
Please open a GitHub issue at https://github.com/Intelligence-AI/jsonschema
```

**Comment by jviotti** [comment]
Hey @lpsinger, thanks for the request. Take it for granted. I'll let you know once its there.

**Comment by jviotti** [comment]
The builds are being produced and I'm releasing v0.5.0 with it.

**Comment by jviotti** [comment]
Done! https://github.com/Intelligence-AI/jsonschema/releases/tag/v0.5.0
